# Generated by Django 5.0.2 on 2024-02-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catch',
            name='length_privacy',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='location_privacy',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='lure_privacy',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='method_privacy',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='time_privacy',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='weather_privacy',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='weight_privacy',
        ),
        migrations.AddField(
            model_name='catch',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catch',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
