# Generated by Django 5.0.2 on 2024-02-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0002_remove_catch_length_privacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catch',
            name='image_filter',
        ),
    ]
