# Generated by Django 5.0.2 on 2024-02-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0003_remove_catch_image_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catch',
            old_name='title',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='catch',
            name='content',
        ),
    ]
